name: Publish to NuGet

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish Release to NuGet
    runs-on: ubuntu-latest
    environment:
      name: "Publish Release"
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Publish NuGet
      uses: alirezanet/publish-nuget@v3.0.4
      with:
        PROJECT_FILE_PATH: src/NuGet.Workflow/NuGet.Workflow.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
